language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - npm run lint

#after_success:
#  - npm run codecov

before_deploy: |
  function npm_dist_tag() {
    if [[ "$TRAVIS_TAG" = *"-"* ]]; then
      echo "next"
    else
      echo "latest"
    fi
  }

deploy:
  provider: npm
  email: kuitos.lau@gmail.com
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
  tag: $(npm_dist_tag)
